[tool.poetry]
name = "upstash_redis_a"
version = "0.1.4"
description = ""
authors = ["Zgîmbău Tudor <tudor.zgimbau@gmail.com>"]
readme = "README.md"
packages = [{ include = "upstash_redis" }]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.4"
pytest = "^7.3.0"
pytest-asyncio = "^0.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
